[project]
authors = ["conda contributors"]
channels = ["conda-forge"]
description = "A pytest plugin to run conda solver tests"
license = "BSD-3-Clause"
license-file = "LICENSE"
name = "pytest-conda-solvers"
platforms = ["linux-64", "osx-64", "win-64"]
readme = "README.md"

[dependencies]
python = ">=3.12"
conda = "*"
fastapi = "*"
fastapi-cache2 = "*"
importlib_resources = ">=5.10"
msgspec = "*"
pytest = ">=6.2.0"
typer = ">=0.15.1,<0.16"

[pypi-dependencies]
pytest-conda-solvers = {path = ".", editable = true}

[tasks]
generate-schema = "python -m pytest_conda_solvers.cli"
test-classic-solver = "pytest --conda-solver=classic conda-solver-tests"
test-libmamba-solver = "pytest --conda-solver=libmamba conda-solver-tests"

[feature.docs.dependencies]
conda-sphinx-theme = "*"
linkify-it-py = "*"
myst-parser = "*"
sphinx = "*"
sphinx-copybutton = "*"
sphinx-design = "*"
sphinx-jsonschema = "*"
sphinx-reredirects = "*"
sphinx-sitemap = "*"
sphinxcontrib-openapi = "*"
sphinxcontrib-programoutput = "*"

[feature.docs.tasks]
docs = {cmd = "python -m sphinx.cmd.build -M dirhtml . _build", cwd = "docs"}
serve = {cmd = "python -m http.server", cwd = "docs/_build/dirhtml"}
clean = {cmd = "rm -rf _build", cwd = "docs"}

[environments]
docs = ["docs"]
